const { HTTP_STATUS } = require('./httpStatus');
const { ERROR_CODES } = require('./codes');

const ERROR_STATUS = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.AUTH_EMAIL_NOT_VERIFIED]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.AUTH_TOKEN_MISSING]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_TOKEN_INVALID]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_REFRESH_TOKEN_MISSING]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_REFRESH_TOKEN_INVALID]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_REFRESH_TOKEN_EXPIRED]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_REFRESH_TOKEN_REVOKED]: HTTP_STATUS.UNAUTHORIZED,

  [ERROR_CODES.USER_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.USER_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.USER_USERNAME_TAKEN]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.USER_EMAIL_TAKEN]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.PASSWORD_INVALID]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.PASSWORD_TOO_WEAK]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.PASSWORD_SAME_AS_CURRENT]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.PASSWORD_RESET_TOKEN_INVALID]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.PASSWORD_RESET_TOKEN_EXPIRED]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.EMAIL_SEND_FAILED]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.EMAIL_SAME_AS_CURRENT]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.EMAIL_VERIFICATION_FAILED]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.EMAIL_CHANGE_TOKEN_INVALID]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.EMAIL_CHANGE_TOKEN_EXPIRED]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.VALIDATION_FAILED]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.SESSION_START_ONLY_ON_SCHEDULED_DAY]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.SESSION_MARK_FINISHED_TOO_EARLY]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.SESSION_TIME_CONFLICT_OWNER]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.SESSION_TIME_CONFLICT_PLAYER]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.SESSION_OWNER_ONLY]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.SESSION_GM_ONLY]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.SESSION_GM_ALREADY_EXISTS]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.SESSION_NO_GM_KICK_ACTIVE]: HTTP_STATUS.CONFLICT,
  [ERROR_CODES.SESSION_DELETE_FORBIDDEN]: HTTP_STATUS.CONFLICT,

  [ERROR_CODES.CAMPAIGN_TRANSFER_FAILED]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.CAMPAIGN_OWNER_REQUIRED]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.CAMPAIGN_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.CAMPAIGN_FINISHED]: HTTP_STATUS.CONFLICT,

  [ERROR_CODES.FILE_INVALID_FORMAT]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.FILE_TOO_LARGE]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.FILE_UPLOAD_FAILED]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: HTTP_STATUS.TOO_MANY_REQUESTS,
  [ERROR_CODES.RATE_LIMIT_UNAVAILABLE]: HTTP_STATUS.SERVICE_UNAVAILABLE,

  [ERROR_CODES.ADMIN_ACCESS_DENIED]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.ADMIN_CANNOT_DELETE_SELF]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.ADMIN_RESOURCE_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,

  [ERROR_CODES.SECURITY_CSRF_INVALID]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.SECURITY_CORS_BLOCKED]: HTTP_STATUS.FORBIDDEN,
  [ERROR_CODES.SECURITY_ACCESS_DENIED]: HTTP_STATUS.FORBIDDEN,

  [ERROR_CODES.SERVER_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.SERVER_UNAVAILABLE]: HTTP_STATUS.SERVICE_UNAVAILABLE,
  [ERROR_CODES.DATABASE_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
};

module.exports = { ERROR_STATUS };